# -*- coding: utf-8 -*-
"""semEval_B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBlOTe4lGgMvHzWw772CP7tm827uRrjM
"""

model_name = "Qwen/Qwen2.5-Coder-3B-Instruct"
train_type = "train_on_response_only"

from datasets import load_dataset
import pandas as pd

# Load Subtask A data
ds = load_dataset("DaniilOr/SemEval-2026-Task13", "A")

# Explore structure
print(ds['train'].column_names)
print(ds['train'][0])

# Convert to DataFrame for EDA
train_df = pd.DataFrame(ds['train'])
print(train_df['label'].value_counts())
print(train_df['generator'].value_counts())
print(train_df['language'].value_counts())

# SemEval-2026 Task 13: Detecting Machine-Generated Code
# Starter Notebook Setup

# ============================================================================
# 1. IMPORTS AND SETUP
# ============================================================================

import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter, defaultdict
import warnings
warnings.filterwarnings('ignore')

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

print("✓ Basic imports loaded")

# ============================================================================
# 2. DATASET LOADING
# ============================================================================

def load_semeval_data(subtask='A', split='train'):
    """
    Load SemEval-2026 Task 13 data

    Args:
        subtask: 'A' (binary), 'B' (multiclass), or 'C' (hybrid)
        split: 'train', 'test', 'validation'

    Returns:
        Dataset object or DataFrame
    """
    try:
        from datasets import load_dataset

        print(f"Loading Subtask {subtask}, {split} split...")
        ds = load_dataset("DaniilOr/SemEval-2026-Task13", subtask)

        if split in ds:
            return ds[split]
        else:
            print(f"Available splits: {list(ds.keys())}")
            return ds

    except Exception as e:
        print(f"Error loading dataset: {e}")
        print("Make sure to: pip install datasets")
        return None


def dataset_to_dataframe(dataset):
    """Convert HuggingFace dataset to pandas DataFrame"""
    return pd.DataFrame(dataset)


# Load all three subtasks
print("\nLoading datasets...")
ds_a_train = load_semeval_data('A', 'train')
ds_b_train = load_semeval_data('B', 'train')
ds_c_train = load_semeval_data('C', 'train')

# Convert to DataFrames
df_a = dataset_to_dataframe(ds_a_train) if ds_a_train else None
df_b = dataset_to_dataframe(ds_b_train) if ds_b_train else None
df_c = dataset_to_dataframe(ds_c_train) if ds_c_train else None

print("✓ Datasets loaded")

# ============================================================================
# 3. EXPLORATORY DATA ANALYSIS
# ============================================================================

def analyze_dataset(df, subtask_name, description=""):
    """
    Comprehensive EDA for a subtask dataset

    Args:
        df: DataFrame to analyze
        subtask_name: 'A', 'B', or 'C'
        description: Optional description
    """
    print(f"\n{'='*70}")
    print(f"SUBTASK {subtask_name}: {description}")
    print(f"{'='*70}")

    # Basic info
    print(f"\nDataset shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")

    # Data types
    print(f"\nData types:\n{df.dtypes}")

    # Missing values
    print(f"\nMissing values:\n{df.isnull().sum()}")

    # Label distribution
    if 'label' in df.columns:
        print(f"\nLabel distribution:")
        print(df['label'].value_counts().sort_index())
        print(f"\nLabel proportions:")
        print(df['label'].value_counts(normalize=True).sort_index())

    # Generator distribution
    if 'generator' in df.columns:
        print(f"\nGenerator distribution:")
        print(df['generator'].value_counts())

    # Language distribution
    if 'language' in df.columns:
        print(f"\nLanguage distribution:")
        print(df['language'].value_counts())

    # Code statistics
    if 'code' in df.columns:
        df['code_length'] = df['code'].str.len()
        df['code_lines'] = df['code'].str.count('\n')

        print(f"\nCode statistics:")
        print(f"  Mean length: {df['code_length'].mean():.0f} chars")
        print(f"  Median length: {df['code_length'].median():.0f} chars")
        print(f"  Mean lines: {df['code_lines'].mean():.1f} lines")
        print(f"  Max length: {df['code_length'].max()} chars")
        print(f"  Min length: {df['code_length'].min()} chars")

    # Sample
    print(f"\nSample rows:")
    print(df.head(2))

    return df


# Run EDA for each subtask
if df_a is not None:
    df_a = analyze_dataset(df_a, 'A', 'Binary Machine-Generated Code Detection')

if df_b is not None:
    df_b = analyze_dataset(df_b, 'B', 'Multi-Class Authorship Detection')

if df_c is not None:
    df_c = analyze_dataset(df_c, 'C', 'Hybrid Code Detection')

# ============================================================================
# 4. DATA VISUALIZATION
# ============================================================================

def visualize_dataset(df, subtask_name):
    """Create visualizations for dataset analysis"""

    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle(f'Subtask {subtask_name} - Data Distribution', fontsize=16, fontweight='bold')

    # Label distribution
    if 'label' in df.columns:
        label_counts = df['label'].value_counts().sort_index()
        axes[0, 0].bar(label_counts.index, label_counts.values, color='steelblue')
        axes[0, 0].set_xlabel('Label')
        axes[0, 0].set_ylabel('Count')
        axes[0, 0].set_title('Label Distribution')
        axes[0, 0].grid(axis='y', alpha=0.3)

    # Generator distribution
    if 'generator' in df.columns:
        gen_counts = df['generator'].value_counts().head(10)
        axes[0, 1].barh(range(len(gen_counts)), gen_counts.values, color='coral')
        axes[0, 1].set_yticks(range(len(gen_counts)))
        axes[0, 1].set_yticklabels(gen_counts.index, fontsize=9)
        axes[0, 1].set_xlabel('Count')
        axes[0, 1].set_title('Top 10 Generators')
        axes[0, 1].grid(axis='x', alpha=0.3)

    # Language distribution
    if 'language' in df.columns:
        lang_counts = df['language'].value_counts()
        axes[1, 0].bar(lang_counts.index, lang_counts.values, color='lightgreen')
        axes[1, 0].set_xlabel('Language')
        axes[1, 0].set_ylabel('Count')
        axes[1, 0].set_title('Language Distribution')
        axes[1, 0].grid(axis='y', alpha=0.3)

    # Code length distribution
    if 'code' in df.columns:
        code_length = df['code'].str.len()
        axes[1, 1].hist(code_length, bins=50, color='mediumpurple', alpha=0.7, edgecolor='black')
        axes[1, 1].set_xlabel('Code Length (characters)')
        axes[1, 1].set_ylabel('Frequency')
        axes[1, 1].set_title('Code Length Distribution')
        axes[1, 1].grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plt.savefig(f'subtask_{subtask_name}_eda.png', dpi=300, bbox_inches='tight')
    plt.show()
    print(f"✓ Visualization saved as 'subtask_{subtask_name}_eda.png'")


# Create visualizations
if df_a is not None:
    visualize_dataset(df_a, 'A')

if df_b is not None:
    visualize_dataset(df_b, 'B')

# ============================================================================
# 5. CODE SAMPLE ANALYSIS
# ============================================================================

def show_code_samples(df, subtask_name, n_samples=3):
    """Display sample code snippets"""
    print(f"\n{'='*70}")
    print(f"CODE SAMPLES - Subtask {subtask_name}")
    print(f"{'='*70}")

    for idx in range(min(n_samples, len(df))):
        row = df.iloc[idx]
        print(f"\n--- Sample {idx+1} ---")
        if 'label' in row:
            print(f"Label: {row['label']}")
        if 'generator' in row:
            print(f"Generator: {row['generator']}")
        if 'language' in row:
            print(f"Language: {row['language']}")

        print(f"\nCode (first 500 chars):")
        code = row['code']
        print(code[:500] if len(code) > 500 else code)
        if len(code) > 500:
            print(f"... [truncated, total {len(code)} chars]")


# Show samples
if df_a is not None:
    show_code_samples(df_a, 'A', n_samples=2)

# ============================================================================
# 6. LABEL MAPPINGS
# ============================================================================

def create_label_mapping(df, subtask_name):
    """Create label to ID mappings"""
    if 'label' in df.columns:
        unique_labels = sorted(df['label'].unique())
        label_to_id = {label: idx for idx, label in enumerate(unique_labels)}
        id_to_label = {idx: label for label, idx in label_to_id.items()}

        print(f"\nLabel mappings for Subtask {subtask_name}:")
        for id_, label in id_to_label.items():
            print(f"  {id_}: {label}")

        return label_to_id, id_to_label
    return None, None


# Create mappings
if df_a is not None:
    label_to_id_a, id_to_label_a = create_label_mapping(df_a, 'A')

if df_b is not None:
    label_to_id_b, id_to_label_b = create_label_mapping(df_b, 'B')

# ============================================================================
# 7. DATA QUALITY CHECKS
# ============================================================================

def check_data_quality(df, subtask_name):
    """Identify potential data quality issues"""
    print(f"\n{'='*70}")
    print(f"DATA QUALITY CHECK - Subtask {subtask_name}")
    print(f"{'='*70}")

    issues = []

    # Check for empty codes
    if 'code' in df.columns:
        empty_codes = (df['code'].str.len() == 0).sum()
        if empty_codes > 0:
            issues.append(f"  ⚠ {empty_codes} empty code snippets")

    # Check for duplicates
    if 'code' in df.columns:
        duplicates = df['code'].duplicated().sum()
        if duplicates > 0:
            issues.append(f"  ⚠ {duplicates} duplicate code snippets")

    # Check for null values
    null_cols = df.isnull().sum()
    if null_cols.sum() > 0:
        for col, count in null_cols[null_cols > 0].items():
            issues.append(f"  ⚠ {count} null values in '{col}'")

    # Check for imbalanced labels
    if 'label' in df.columns:
        label_dist = df['label'].value_counts()
        max_count = label_dist.max()
        min_count = label_dist.min()
        imbalance_ratio = max_count / min_count if min_count > 0 else float('inf')

        if imbalance_ratio > 2:
            issues.append(f"  ⚠ Imbalanced labels (ratio: {imbalance_ratio:.2f})")

    # Check for garbled/corrupted code
    if 'code' in df.columns:
        # Simple heuristic: look for high proportion of special chars
        def has_suspicious_chars(code_str):
            total_chars = len(code_str)
            if total_chars == 0:
                return False
            special_chars = sum(1 for c in code_str if not c.isalnum() and c not in ' \n\t()[]{}.:,;"\'-')
            return special_chars / total_chars > 0.5

        corrupted = df['code'].apply(has_suspicious_chars).sum()
        if corrupted > 0:
            issues.append(f"  ℹ {corrupted} potentially corrupted/garbled code snippets")

    if not issues:
        print("✓ No major data quality issues detected")
    else:
        print("Issues found:")
        for issue in issues:
            print(issue)

    return issues


# Run quality checks
if df_a is not None:
    check_data_quality(df_a, 'A')

if df_b is not None:
    check_data_quality(df_b, 'B')

if df_c is not None:
    check_data_quality(df_c, 'C')

# ============================================================================
# 8. PREPROCESSING UTILITIES
# ============================================================================

def preprocess_code(code_str):
    """
    Basic code preprocessing
    - Strip whitespace
    - Remove comments (basic)
    - Normalize indentation
    """
    # Strip leading/trailing whitespace
    code = code_str.strip()

    # Remove single-line comments (simple heuristic)
    lines = code.split('\n')
    lines = [line.split('#')[0].rstrip() for line in lines]  # Python comments
    code = '\n'.join(lines)

    return code


def extract_code_features(code_str):
    """Extract basic features from code"""
    features = {
        'length': len(code_str),
        'lines': code_str.count('\n'),
        'indent_levels': len(set(len(line) - len(line.lstrip()) for line in code_str.split('\n'))),
        'avg_line_length': np.mean([len(line) for line in code_str.split('\n')]) if code_str.count('\n') > 0 else 0,
        'has_docstring': '"""' in code_str or "'''" in code_str,
        'has_type_hints': ':' in code_str,  # Simple heuristic
        'unique_tokens': len(set(code_str.split())),
    }
    return features


# ============================================================================
# 9. SUMMARY STATISTICS
# ============================================================================

print(f"\n{'='*70}")
print("SUMMARY STATISTICS")
print(f"{'='*70}")

summary = {
    'Subtask A (Binary)': df_a.shape[0] if df_a is not None else 0,
    'Subtask B (Multi-class)': df_b.shape[0] if df_b is not None else 0,
    'Subtask C (Hybrid)': df_c.shape[0] if df_c is not None else 0,
}

for subtask, count in summary.items():
    print(f"{subtask}: {count:,} samples")

print(f"\n{'='*70}")
print("✓ Notebook setup complete!")
print(f"{'='*70}")

print("""
Next steps:
1. Explore individual code samples more deeply
2. Extract linguistic and structural features
3. Choose a baseline model (CodeBERT, StarCoder, etc.)
4. Set up training pipeline
5. Evaluate on different generalization settings

Available DataFrames:
- df_a: Subtask A (Binary)
- df_b: Subtask B (Multi-class)
- df_c: Subtask C (Hybrid)

Key functions:
- load_semeval_data(subtask, split)
- preprocess_code(code_str)
- extract_code_features(code_str)
""")

# Example: Extract features
def extract_basic_features(code_str):
    features = {
        'length': len(code_str),
        'lines': code_str.count('\n'),
        'has_comments': '#' in code_str,
        'has_docstring': '"""' in code_str or "'''" in code_str,
        'has_try_except': 'try:' in code_str and 'except' in code_str,
        'avg_line_length': np.mean([len(l) for l in code_str.split('\n')]),
    }
    return features

import torch
import numpy as np
import pandas as pd
from transformers import RobertaTokenizer, RobertaModel
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

# Define the get_embeddings function
def get_embeddings(code_samples_list, tokenizer, model, device='cpu', batch_size=32):
    model.eval() # Set model to evaluation mode
    embeddings = []

    # Ensure code_samples_list is a list of strings
    if isinstance(code_samples_list, pd.Series):
        code_samples_list = code_samples_list.tolist()

    for i in range(0, len(code_samples_list), batch_size):
        batch_codes = code_samples_list[i:i + batch_size]
        # Tokenize batch
        inputs = tokenizer(batch_codes, return_tensors='pt', padding=True, truncation=True, max_length=512)
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)
        # Use the [CLS] token embedding for sentence representation
        batch_embeddings = outputs.last_hidden_state[:, 0, :].cpu().numpy()
        embeddings.append(batch_embeddings)
    return np.vstack(embeddings) if embeddings else np.array([])


# Load CodeBERT
print("Loading CodeBERT tokenizer and model...")
tokenizer = RobertaTokenizer.from_pretrained("microsoft/codebert-base")
model = RobertaModel.from_pretrained("microsoft/codebert-base")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print(f"CodeBERT loaded to device: {device}")


# Prepare data (using df_a as an example for binary classification)
if 'df_a' in globals() and not df_a.empty:
    print("Preparing data from df_a for Subtask A (Binary Classification)...")
    # Using a subset for faster demonstration. For full training, use df_a directly.
    df_subset = df_a.sample(n=min(len(df_a), 10000), random_state=42).copy() # Use a sample for speed

    code_samples_full = df_subset['code']
    labels_full = df_subset['label']

    # Perform train-test split
    code_train, code_test, labels_train, labels_test = train_test_split(
        code_samples_full, labels_full, test_size=0.2, random_state=42, stratify=labels_full
    )
    print(f"Train samples: {len(code_train)}, Test samples: {len(code_test)}")

    # Get embeddings for training data
    print("Getting embeddings for training data...")
    embeddings_train = get_embeddings(code_train, tokenizer, model, device=device)
    print("Getting embeddings for test data...")
    embeddings_test = get_embeddings(code_test, tokenizer, model, device=device)

    # Train classifier
    print("Training Logistic Regression classifier...")
    clf = LogisticRegression(max_iter=1000, solver='liblinear') # Increased max_iter and specified solver for convergence
    clf.fit(embeddings_train, labels_train)

    # Evaluate
    print("Evaluating classifier...")
    f1 = f1_score(labels_test, clf.predict(embeddings_test), average='macro')
    print(f"F1 Score (macro) on Subtask A (sample): {f1:.4f}")

else:
    print("DataFrame 'df_a' not found or empty. Please ensure data is loaded.")
    print("Cannot proceed with embedding and classification without data.")

# 1. Install
!pip install jupyter datasets transformers scikit-learn pandas numpy xgboost torch

# 2. Run (Note: Running jupyter notebook directly in Colab is generally not needed as Colab is already a Jupyter environment)
!jupyter notebook semeval_2026_task13.ipynb

# 3. Code (use TASK_A_ONLY.md for template)

from datasets import load_dataset
dsB = load_dataset("DaniilOr/SemEval-2026-Task13", "B")
print(dsB)
print(dsB["train"].column_names)
print(dsB["train"][0])